In [1]:
import fast_attention 
import fast_attention_sonnet
import tensorflow as tf

In [7]:
att = fast_attention.Attention(16,2,.1)

In [2]:
q = tf.random.uniform(shape=[3,4,2])
k = tf.random.uniform(shape=[3,4,2])
v = tf.random.uniform(shape=[3,4,2])

2021-07-19 23:50:56.480778: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-07-19 23:50:56.481149: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [9]:
att(q,k,v, training=False)

<tf.Tensor: shape=(3, 4, 16), dtype=float32, numpy=
array([[[-0.18411647, -0.04235095,  0.22154942, -0.0676275 ,
         -0.27551848, -0.5635143 , -0.212014  ,  0.0985232 ,
         -0.21964404,  0.34877256,  0.4430136 ,  0.057391  ,
         -0.14075099, -0.19116862, -0.06790448, -0.24783257],
        [-0.16661733, -0.04078298,  0.22091903, -0.07945228,
         -0.25376654, -0.5837271 , -0.19992425,  0.07957981,
         -0.21986705,  0.36471668,  0.4538509 ,  0.06387669,
         -0.12456175, -0.19875494, -0.05377022, -0.25271928],
        [-0.11854018, -0.03875249,  0.1777253 , -0.11206058,
         -0.22173025, -0.6214761 , -0.17039028,  0.02582404,
         -0.2220481 ,  0.41227418,  0.4840657 ,  0.08351396,
         -0.06989419, -0.14529051, -0.03501548, -0.26005796],
        [-0.12096417, -0.03864601,  0.1836499 , -0.11040035,
         -0.22083527, -0.62115324, -0.1715461 ,  0.02869858,
         -0.22178757,  0.4095154 ,  0.482482  ,  0.0823511 ,
         -0.07357418, -0.15470

In [3]:
d = fast_attention_sonnet.DenseEinsum(output_shape=[3, 4])

In [4]:
q

<tf.Tensor: shape=(3, 4, 2), dtype=float32, numpy=
array([[[0.9463624 , 0.875126  ],
        [0.6477612 , 0.25701904],
        [0.67324865, 0.420282  ],
        [0.02375185, 0.3321097 ]],

       [[0.75548947, 0.91775477],
        [0.8243774 , 0.16390991],
        [0.39590907, 0.7915007 ],
        [0.67535925, 0.9815544 ]],

       [[0.40092528, 0.14905155],
        [0.9759133 , 0.04588139],
        [0.5841346 , 0.34549594],
        [0.7322705 , 0.4629532 ]]], dtype=float32)>

In [5]:
d(q)

<tf.Tensor: shape=(3, 4, 3, 4), dtype=float32, numpy=
array([[[[ 0.26772243, -0.33337727,  0.63552725,  0.48005474],
         [ 0.40005016,  0.26231515,  0.6457148 ,  0.94156957],
         [-0.67562425,  0.14656454, -0.7160816 ,  0.56872886]],

        [[ 0.07729029, -0.19906929,  0.42007044,  0.3764237 ],
         [ 0.13574243,  0.0796403 ,  0.35510367,  0.5175619 ],
         [-0.30052814,  0.03474991, -0.374956  ,  0.2110861 ]],

        [[ 0.12778302, -0.21994245,  0.44328588,  0.36981142],
         [ 0.20292065,  0.1275156 ,  0.40797976,  0.5947644 ],
         [-0.38486546,  0.06548133, -0.44129217,  0.2991925 ]],

        [[ 0.10281402, -0.03477535,  0.02949236, -0.03133635],
         [ 0.13526757,  0.09719048,  0.09499071,  0.13873476],
         [-0.16380255,  0.06314408, -0.12243303,  0.17587945]]],


       [[[ 0.28162107, -0.2847968 ,  0.516915  ,  0.35257837],
         [ 0.407843  ,  0.27342692,  0.5711452 ,  0.83298963],
         [-0.6431109 ,  0.15901928, -0.6454612 ,  0.56

In [3]:
at = fast_attention_sonnet.Attention(16,2,.1)

In [4]:
at(q,k,v, training=False)

(2, 2, 8)
tf.Tensor(
[[[-0.04083711 -0.50937396  0.2947538   0.49913263  0.48731947
   -0.488171    0.45297062  0.20162433]
  [-0.35118735 -0.48102605 -0.5052095  -0.38140315  0.04238015
    0.2910176   0.3258443  -0.2536764 ]]

 [[-0.07063007  0.33799034 -0.14918494  0.22882527  0.24527758
    0.04973143 -0.4673724  -0.13839388]
  [-0.26980132 -0.301239   -0.3147586   0.32021296 -0.4681593
    0.13827688 -0.3241405  -0.18332595]]], shape=(2, 2, 8), dtype=float32)
(2, 2, 8)
tf.Tensor(
[[[ 0.4707868   0.5379522   0.50483024  0.13152081  0.45028973
   -0.4282465   0.18887854 -0.1595712 ]
  [ 0.00403202 -0.47473267 -0.43934038  0.00993156 -0.51828873
    0.5397513  -0.10779637  0.31429094]]

 [[ 0.49867475  0.22138429  0.31532717 -0.44958743 -0.37905023
    0.29970998  0.03218246  0.10364318]
  [-0.43025178 -0.05316362  0.4451005   0.50197065  0.48194587
    0.04536825  0.00480729 -0.4130259 ]]], shape=(2, 2, 8), dtype=float32)
None
abc,cde->abde
(2, 2, 8)
tf.Tensor(
[[[-0.20902017 -0.276

AttributeError: 'NoneType' object has no attribute 'shape'