In [1]:
import fast_attention 
import fast_attention_sonnet
import tensorflow as tf

In [8]:
att = fast_attention.Attention(16,2,.1)

In [2]:
q = tf.random.uniform(shape=[3,4,2])
k = tf.random.uniform(shape=[3,4,2])
v = tf.random.uniform(shape=[3,4,2])

In [9]:
att(q,k,v)

<tf.Tensor: shape=(3, 4, 16), dtype=float32, numpy=
array([[[-0.27424893,  0.22196783, -0.03687441, -0.02671474,
          0.10252777,  0.00707454, -0.23470871,  0.38457868,
         -0.0529622 , -0.18802114, -0.18326248,  0.00861461,
         -0.28555307, -0.3202009 , -0.40292683,  0.22019295],
        [-0.28632876,  0.16821244, -0.04017401, -0.06224463,
          0.07455747,  0.00454378, -0.18839459,  0.35851562,
         -0.02480724, -0.15737475, -0.21974528,  0.00775389,
         -0.24437115, -0.25265753, -0.33859015,  0.18129414],
        [-0.27821115,  0.22252497, -0.03857093, -0.02913769,
          0.10210926,  0.00872578, -0.234504  ,  0.38595957,
         -0.05195307, -0.1870086 , -0.19054571,  0.00816536,
         -0.2867438 , -0.31864622, -0.39904916,  0.2191246 ],
        [-0.29295537,  0.1818733 , -0.04318384, -0.05988677,
          0.08018579,  0.00807775, -0.19874133,  0.3686175 ,
         -0.02767111, -0.16244854, -0.2268931 ,  0.00715152,
         -0.25603175, -0.26566

In [3]:
d = fast_attention_sonnet.DenseEinsum(output_shape=[3, 4])

In [4]:
q

<tf.Tensor: shape=(3, 4, 2), dtype=float32, numpy=
array([[[0.9463624 , 0.875126  ],
        [0.6477612 , 0.25701904],
        [0.67324865, 0.420282  ],
        [0.02375185, 0.3321097 ]],

       [[0.75548947, 0.91775477],
        [0.8243774 , 0.16390991],
        [0.39590907, 0.7915007 ],
        [0.67535925, 0.9815544 ]],

       [[0.40092528, 0.14905155],
        [0.9759133 , 0.04588139],
        [0.5841346 , 0.34549594],
        [0.7322705 , 0.4629532 ]]], dtype=float32)>

In [5]:
d(q)

<tf.Tensor: shape=(3, 4, 3, 4), dtype=float32, numpy=
array([[[[ 0.26772243, -0.33337727,  0.63552725,  0.48005474],
         [ 0.40005016,  0.26231515,  0.6457148 ,  0.94156957],
         [-0.67562425,  0.14656454, -0.7160816 ,  0.56872886]],

        [[ 0.07729029, -0.19906929,  0.42007044,  0.3764237 ],
         [ 0.13574243,  0.0796403 ,  0.35510367,  0.5175619 ],
         [-0.30052814,  0.03474991, -0.374956  ,  0.2110861 ]],

        [[ 0.12778302, -0.21994245,  0.44328588,  0.36981142],
         [ 0.20292065,  0.1275156 ,  0.40797976,  0.5947644 ],
         [-0.38486546,  0.06548133, -0.44129217,  0.2991925 ]],

        [[ 0.10281402, -0.03477535,  0.02949236, -0.03133635],
         [ 0.13526757,  0.09719048,  0.09499071,  0.13873476],
         [-0.16380255,  0.06314408, -0.12243303,  0.17587945]]],


       [[[ 0.28162107, -0.2847968 ,  0.516915  ,  0.35257837],
         [ 0.407843  ,  0.27342692,  0.5711452 ,  0.83298963],
         [-0.6431109 ,  0.15901928, -0.6454612 ,  0.56

In [3]:
at = fast_attention_sonnet.Attention(16,2,.1, nb_random_features=8)

In [4]:
at

Attention(
    hidden_size=16,
    num_heads=2,
    attention_dropout=0.1,
    nb_random_features=8,
)

In [5]:
at(q,k,v, training=False)

(3, 4, 2, 8) (3, 4, 2, 8) (3, 4, 2, 8)
8 tf.Tensor(753772800, shape=(), dtype=int32)
8


<tf.Tensor: shape=(3, 4, 16), dtype=float32, numpy=
array([[[ 0.04286792,  0.0675773 ,  0.05343106,  0.23555358,
          0.27375945,  0.00488367,  0.0742912 , -0.05260586,
          0.03539731, -0.07552905,  0.09196819, -0.07986923,
         -0.2774785 , -0.14816532, -0.04718183, -0.08503211],
        [ 0.04199624,  0.06781008,  0.05304343,  0.23429258,
          0.27374163,  0.00486747,  0.0743136 , -0.05256416,
          0.0357716 , -0.07550967,  0.09081673, -0.07953504,
         -0.2768347 , -0.14730199, -0.04725787, -0.08495343],
        [ 0.04294147,  0.06753824,  0.0534314 ,  0.23567398,
          0.2736236 ,  0.00486519,  0.07424767, -0.05259628,
          0.03529025, -0.07554526,  0.09208146, -0.07991502,
         -0.27739757, -0.14820948, -0.04712642, -0.08500832],
        [ 0.04221408,  0.06777017,  0.05313217,  0.23463777,
          0.27367255,  0.00486267,  0.07425917, -0.05258537,
          0.03561814, -0.07554789,  0.09110638, -0.07964528,
         -0.276929  , -0.14750

In [10]:
sa= fast_attention_sonnet.SelfAttention(16,2,.1, nb_random_features=8)

In [12]:
sa(q, training=False)

(3, 4, 2, 8) (3, 4, 2, 8) (3, 4, 2, 8)
8 tf.Tensor(487131744, shape=(), dtype=int32)
8


<tf.Tensor: shape=(3, 4, 16), dtype=float32, numpy=
array([[[ 0.07139841,  0.21669698, -0.11457706, -0.04723755,
          0.12818968,  0.04149307,  0.21681213, -0.04418435,
          0.22506157,  0.18410867, -0.11961072, -0.02390155,
         -0.00415642,  0.2195761 ,  0.05087456,  0.01419778],
        [ 0.07147913,  0.21711555, -0.11446731, -0.04618834,
          0.12847659,  0.04093508,  0.21645793, -0.04362581,
          0.22524297,  0.18401846, -0.12016822, -0.02344617,
         -0.00311799,  0.2192045 ,  0.05103756,  0.0140913 ],
        [ 0.07138082,  0.21681954, -0.11459384, -0.04698807,
          0.12835005,  0.04125822,  0.21675448, -0.04400579,
          0.22505696,  0.1841262 , -0.11976571, -0.02378742,
         -0.00378718,  0.21951939,  0.05094282,  0.01405406],
        [ 0.0715238 ,  0.21698663, -0.11445525, -0.04631745,
          0.1283937 ,  0.041008  ,  0.21648812, -0.04363558,
          0.2251774 ,  0.18408315, -0.12000784, -0.02350368,
         -0.00331985,  0.21920